### ISSUE TITLE
Adding autocomplete

### ISSUE THREAD

**Issue by manuel-uberti** [arttuka/reagent-material-ui#1]
Hi,

first of all thanks for this project, it's proven to be very useful.

Do you think there is a chance a component like [Autocomplete](https://material-ui.com/components/autocomplete/) can be added?

**Comment by alenkralj** [comment]
Hi, 

I would also like to thank @arttuka for this awesome project. I would also use Autocomplete :smiley:

**Comment by alenkralj** [comment]
I have made PR for `cljsjs/packages` to provide `material-ui-lab` - https://github.com/cljsjs/packages/pull/2063.

**Comment by manuel-uberti** [comment]
Thank you @alenkralj, let's hope @arttuka jumps in now. :)

**Comment by alenkralj** [comment]
@manuel-uberti I'm trying to add lab components to `reagent-material-ui`, but I'm having some issues with `Autocomplete` component which we both want to use. I'm guessing I did not correctly convert data from javascript to clojure. I have tried `Rating` component and it works fine. I can push changes onto my repo, so that someone smarter than me can look at it.

**Comment by alenkralj** [comment]
@manuel-uberti I have finally managed to figure out how to use Autocomplete thanks to this source: https://github.com/reagent-project/reagent/blob/master/examples/material-ui/src/example/core.cljs . Nothing is wrong with my reagent-material-ui commit. It is just the way one has to use it. Basically `render-input` method has to be written in JS like:
```
(fn [^js params]
 ;; Don't call js->clj because that would recursively
 ;; convert all JS objects (e.g. React ref objects)
 ;; to Cljs maps, which breaks them, even when converted back to JS.
 ;; Best thing is to use r/create-element and
 ;; pass the JS params to it.
 ;; If necessary, use JS interop to modify params.
  (doto params
    (-> .-label (set! label))
    (-> .-placeholder (set! placeholder)))
  (r/create-element (.-TextField js/MaterialUI) params))
```

**Comment by manuel-uberti** [comment]
Thank you for the suggestion and the example. :+1:

**Comment by manuel-uberti** [comment]
Since I'm going to try the suggested approach, I'm going to close this ticket.
