### ISSUE TITLE
React does not recognize the `nodeRef` prop on a DOM element.

### ISSUE THREAD

**Issue by cj-price** [arttuka/reagent-material-ui#12]
I ran into this problem and wasn't sure where to document the fix.

When using `collapse` , or anything that uses `collapse` (like `step-content`), you receive the error:

```
React does not recognize the `nodeRef` prop on a DOM element.
```
To remove the error, one must pass a custom component to `collapse`.
``` clojure
(def node-ref-fix
  (reagent.core/reactify-component
   (fn [props]
     [:div (dissoc props :nodeRef)
      (:children props)])))

(defn my-collapse []
 [collapse {:component node-ref-fix ...}
  ...])
```
For `step-content` you can pass `node-ref-fix` to `:TransitionProps`
``` clojure
[step-content {:TransitionProps {:component node-ref-fix}} ...]
```

I think this is a problem with reagent interop (not the library itself), so I am not sure if this library would like to handle this use case automatically. I see in https://github.com/arttuka/reagent-material-ui/blob/633f330f6d6c6e153ca907511befbf006918c1ad/src/core/reagent_material_ui/core/text_field.cljs#L18 that a similar issue is handled for `text-field`.

**Comment by arttuka** [comment]
This seems to be caused by an outdated version of `react-transition-group` in your project. Try updating it to `4.4.1` and see if the problem still persists.

**Comment by cj-price** [comment]
Thank you! This worked perfectly.
