### ISSUE TITLE
npm error: Could not resolve dependency: peer react@"^16.8.4"

### ISSUE THREAD

**Issue by ccfontes** [arttuka/reagent-material-ui#13]
Just started using `reagent-material-ui`, and got the following npm errors.

❯ clj -M:shadow-cljs watch app
```
running: npm install --save --save-exact @material-ui/core@4.11.2 @material-ui/pickers@3.2.10 @material-ui/lab@4.0.0-alpha.57 react@17.0.1 react-dom@17.0.1
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!   peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.11.2
npm ERR!   node_modules/@material-ui/core
npm ERR!     @material-ui/core@"4.11.2" from the root project
npm ERR!     peer @material-ui/core@"^4.0.0" from @material-ui/pickers@3.2.10
npm ERR!     node_modules/@material-ui/pickers
npm ERR!       @material-ui/pickers@"3.2.10" from the root project
npm ERR!   1 more (react-dom)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.4" from @material-ui/pickers@3.2.10
npm ERR! node_modules/@material-ui/pickers
npm ERR!   @material-ui/pickers@"3.2.10" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

deps.edn:
```clj
{:deps {reagent/reagent {:mvn/version "1.0.0"}
        reagent-utils/reagent-utils {:mvn/version "0.3.3"}
        arttuka/reagent-material-ui {:mvn/version "4.11.2-0"}}
```

Running:
```sh
npm install --save --save-exact --legacy-peer-deps @material-ui/core@4.11.2 @material-ui/pickers@3.2.10 @material-ui/lab@4.0.0-alpha.57 react@17.0.1 react-dom@17.0.1
```
made the errors disappear. So maybe it's fixed.
Is there a cleaner troubleshooting-fu to solve the issue?

**Comment by lucian303** [comment]
I noticed that upgrading shadow to the latest version and using the same version of shadow everywhere often helped with similar problems I've seen working with the `next` (v5) branch.

**Comment by arttuka** [comment]
Looks like the stable version of `material-ui-pickers` doesn't support React 17 yet, my bad for not catching this. I'll downgrade to React 16 for the stable branch. You could also consider using MaterialUI v5 alpha from the [next branch](https://github.com/arttuka/reagent-material-ui/tree/next) of `reagent-material-ui`.

**Comment by ccfontes** [comment]
@arttuka Thanks for your solution.

I was on the stable branch.
Should someone then declare React 16 explicitly in their dependencies?
Perhaps some documentation about the incompatibility could be added to `reagent-material-ui`.
I switched to using re-com in the meantime, so it will be hard to test on my local.

I'm OK with closing the ticket, or leave it open if you wish to make some changes.

**Comment by arttuka** [comment]
This has been fixed in the newest version. `material-ui-pickers` has been updated to support React 17.
