### ISSUE TITLE
There are some problems with example after upgrading shadow-cljs

### ISSUE THREAD

**Issue by DeLaGuardo** [arttuka/reagent-material-ui#20]
This might be not a problem of reagent-material-ui but I would like to report it here as a reference if you don't mind )

After updating shadow-cljs dependency (to the 2.15.1) in example's project.json file rendering stops working and spits a lot of exceptions to the console:
![image](https://user-images.githubusercontent.com/542042/125453180-0863d105-83ea-41f1-bd47-688693b7f34a.png)

**Comment by arttuka** [comment]
This seems to be a problem with Closure Compiler handling the comma operator. The bug appears in the version of shadow-cljs where `:output-feature-set` is bumped to `:es6`. 

Specifically what happens is that the parentheses around the comma operator are moved incorrectly if `:output-feature-set` is `:es6` or higher.
```js
const pulsateKeyframe = (0, _system.keyframes)`template literal`
```
is transpiled into
```js
(_system = 0), _system.keyframes`template literal`
```
compared to the ES5 result of
```js
_system = (0, _system.keyframes)($jscomp$templatelit$1481829048$2)
```

Workarounds are either setting `:compiler-options {:output-feature-set :es5}` or `:js-options {:entry-keys ["module" "browser" "main"]}`.
