### ISSUE TITLE
`[date-time-picker]` totally crashes

### ISSUE THREAD

**Issue by wildwestrom** [arttuka/reagent-material-ui#24]
For some reason I get a whole bunch of errors because certain modules from MUI fail to load. In particular `Button` and `DateTimePicker`.  I can't tell if it's a shadow-cljs problem, a material-ui problem, or a problem with the library.
Using shadow cljs with the example project works fine on my machine.

Here is my project where I'm encountering the issue.
https://github.com/wildwestrom/accounting-app/tree/material-ui-next

<img width="845" alt="Screen Shot 2021-08-20 at 01 23 39" src="https://user-images.githubusercontent.com/77174844/130184245-4d8d8784-99ce-41de-aa13-e62b12df779a.png">

@oxr463, could this be related to #21?

**Comment by wildwestrom** [comment]
https://github.com/wildwestrom/accounting-app/tree/material-ui-next

**Comment by oxr463** [comment]
I'm not sure. I was demoing this library when I encountered that issue and I couldn't get it to work so I took it out.

**Comment by wildwestrom** [comment]
I figured it out. I traced it down to this bit of code.
```cljs
[date-time-picker]
```
So obviously something is wrong with the `date-time-picker` from `@material-ui/lab`.

**Comment by wildwestrom** [comment]
Ok, I feel like a bit of an idiot.
I needed this for it to work.
```cljs
     [date-time-picker
     {:render-input (react-component [props]
                                 [text-field props])}]
```
