### ISSUE TITLE
Support for DataGrid and DataGridPro, and other MUI X pro components

### ISSUE THREAD

**Issue by Okwori** [arttuka/reagent-material-ui#25]
Is there support for pro components such as data-grid and date-range-picker in this library?

**Comment by arttuka** [comment]
Support for DataGrid and DataGridPro added in `5.2.4-0` as `reagent-mui.x.data-grid(-pro)`. DateRangePicker is still in `@mui/lab` so it was already included as `reagent-mui.lab.date-range-picker`.
