### ISSUE TITLE
Icons with multiple paths cause `unique "key" prop` error

### ISSUE THREAD

**Issue by jhacksworth** [arttuka/reagent-material-ui#27]
Icons that have more than one path element cause the following error message:

    Warning: Each child in a list should have a unique "key" prop.

I modified the example project to reproduce the error here: https://github.com/jhacksworth/reagent-material-ui/commit/f5a1ef9e1d42784c77574b423b00709101fbd7f6

and run it with shadow-cljs by:

1. Changing to the `example` directory
2. `npm install`
3. `npm run watch`

Screenshot:

<img width="1926" alt="Screen Shot 2021-10-18 at 5 14 54 PM" src="https://user-images.githubusercontent.com/286057/137807941-8a6c1121-51a3-4c43-af3c-9c0b5043bac9.png">

The `zoom-in` icon has two path elements (two calls to the `e` macro) and causes the error message:

https://github.com/arttuka/reagent-material-ui/blob/8754c2e2923bb6379add666313e297543bdc9df5/src/icons/reagent_mui/icons/zoom_in.cljs#L8

The `face` icon, which only has one path element, does not cause an error message:

https://github.com/arttuka/reagent-material-ui/blob/8754c2e2923bb6379add666313e297543bdc9df5/src/icons/reagent_mui/icons/face.cljs#L8

It looks like 2044 out of 8875 icons have multiple paths in [src/icons/reagent_mui/icons/
](https://github.com/arttuka/reagent-material-ui/tree/8754c2e2923bb6379add666313e297543bdc9df5/src/icons/reagent_mui/icons/)

Thanks for creating this library, it's been a pleasure to use!

**Comment by arttuka** [comment]
Fixed in `5.2.4-0`.

**Comment by jhacksworth** [comment]
Just tried it out and it works great. Cheers! 🍻
