### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by wkok** [arttuka/reagent-material-ui#8]
Just a quick thank you for this library, it really takes the pain out of Reagent/React interop, when using Material-UI

For interest, my work-in-progress hobby project making use of reagent-material-ui can be seen here: 

Demo: https://wkok.github.io/re-frame-buy2let/demo
Source: https://wkok.github.io/re-frame-buy2let/

Keep up the good work!

**Comment by arttuka** [comment]
Thank you for the kind words!
